name: Create Tag on PR merge to master

on:
  pull_request_target:
    branches: [master]
    types: [closed]

permissions:
  contents: write
  pull-requests: read

jobs:
  create_tag_on_merge:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout merged commit
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}
          fetch-depth: 0

      - name: Run local action
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
